dist: precise
language: erlang
otp_release:
  - 19.2
  - 18.3
  - 17.5
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cat /etc/lsb-release; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq firebird2.5-super firebird2.5-dev
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
  - sudo service firebird2.5-super start

script:
  - make test
